name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install Backend dependencies
        run: |
          cd Backend
          npm ci
          
      - name: Install Frontend dependencies
        run: |
          cd Frontend
          npm ci
          
      - name: Lint Backend
        run: |
          cd Backend
          npm run lint
          
      - name: Lint Frontend
        run: |
          cd Frontend
          npm run lint
          
      - name: Type check Frontend
        run: |
          cd Frontend
          npm run type-check
          
      - name: Run Backend tests
        run: |
          cd Backend
          npm test
          
      - name: Build Backend
        run: |
          cd Backend
          npm run build
          
      - name: Build Frontend
        run: |
          cd Frontend
          npm run build